//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aeroport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_12
    {
        public int ID { get; set; }
        public string Name_Pash { get; set; }
        public string Familiya { get; set; }
        public string Otchestvo { get; set; }
        public int Pasport { get; set; }
        public string Grashdanstvo { get; set; }
        public string StranaOtrp { get; set; }
        public string Company { get; set; }
        public string Class { get; set; }
        public string StranaPreb { get; set; }
        public System.DateTime Data { get; set; }
    }
}
